version: v1.0
name: ''
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
apiVersion: v1beta
kind: Secret
metadata:
  name: server-ormconfig-production
data:
  files:
    - path: ormconfig.production.json
      content: PASTE_BASE64_ENCODED_CONTENT_HERE
blocks: []
